services:
  - type: web
    name: chat-http-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.http-backend
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_NSRt8Ysjdn5f@ep-gentle-breeze-adqpxi20-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
        
  - type: web
    name: chat-ws-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.ws-backend
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_NSRt8Ysjdn5f@ep-gentle-breeze-adqpxi20-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
