[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm@9.0.0 && export PATH=$PATH:/root/.npm/_npx/*/node_modules/.bin && cd ../.. && pnpm install --filter ws-backend..."]

[phases.build]
cmds = ["export PATH=$PATH:/root/.npm/_npx/*/node_modules/.bin && cd ../.. && pnpm --filter ws-backend build"]

[start]
cmd = "node ./dist/index.js"
