[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm@9.0.0", "cd ../.. && pnpm install --filter ws-backend..."]

[phases.build]
cmds = ["cd ../.. && pnpm --filter @repo/db exec prisma generate && pnpm --filter ws-backend build"]

[start]
cmd = "node ./dist/index.js"
