[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = []

[phases.install]
cmds = [
  "npm install -g pnpm@9.0.0",
  "export PATH=\"/usr/local/bin:$PATH\" && cd ../.. && pnpm install --filter ws-backend..."
]

[phases.build]
cmds = ["export PATH=\"/usr/local/bin:$PATH\" && cd ../.. && pnpm --filter @repo/db exec prisma generate && pnpm --filter ws-backend build"]

[start]
cmd = "node ./dist/index.js"
