[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter ws-backend build"]

[start]
cmd = "node ./dist/index.js"
