[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.ws-backend"
watchPatterns = ["apps/ws-backend/**", "packages/**"]

[deploy]
startCommand = "node apps/ws-backend/dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
