[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm@9.0.0", "cd ../.. && pnpm install"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter http-backend build"]

[start]
cmd = "cd apps/http-backend && node ./dist/index.js"
