[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = []

[phases.install]
cmds = [
  "corepack enable && corepack prepare pnpm@9.0.0 --activate && cd ../.. && NODE_OPTIONS='--max-old-space-size=4096' pnpm install --filter http-backend... --frozen-lockfile"
]

[phases.build]
cmds = ["cd ../.. && pnpm --filter @repo/db exec prisma generate && pnpm --filter http-backend build"]

[start]
cmd = "node ./dist/index.js"
