[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = []

[phases.install]
cmds = [
  "npm install -g pnpm@9.0.0 && ln -sf $(npm root -g)/pnpm/bin/pnpm.cjs /usr/local/bin/pnpm",
  "cd ../.. && pnpm install --filter http-backend..."
]

[phases.build]
cmds = ["cd ../.. && pnpm --filter @repo/db exec prisma generate && pnpm --filter http-backend build"]

[start]
cmd = "node ./dist/index.js"
