[build]
builder = "dockerfile"
dockerfilePath = "apps/http-backend/Dockerfile"
watchPatterns = ["apps/http-backend/**"]

[build.buildContext]
root = "/"

[deploy]
startCommand = "node apps/http-backend/dist/index.js"
