[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.http-backend"
watchPatterns = ["apps/http-backend/**", "packages/**"]

[deploy]
startCommand = "node apps/http-backend/dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
